version: '3'
services:
  db:
    container_name: challenge3
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      # PGADMIN_DEFAULT_EMAIL: nangcuonga1k45@gmail.com
      # PGADMIN_DEFAULT_PASSWORD: Cuongnguyen2001
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cuongnguyen2001
      POSTGRES_DB: Challenge3
    volumes:
      - postgresdb:/var/lib/postgresql/data
  elasticsearch:
    container_name: es_client
    image: "elasticsearch:7.17.5"
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "c-awd64Fl6I3BvTv6oIf"
      HTTP_PROXY: http://192.168.5.8:3128
      HTTPS_PROXY: http://192.168.5.8:3128
    volumes:
      - elasticsearchdb:/usr/share/elasticsearch/data
  backend:
    # image: "challenge3:1.1"
    build: .
    restart: on-failure
    depends_on:
      - db
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      HTTP_PROXY: http://192.168.5.8:3128
      HTTPS_PROXY: http://192.168.5.8:3128
  portal:
    container_name: portal
    image: challenge7:1.3
    command: ng serve --host 0.0.0.0
    depends_on:
      - backend
    ports:
      - "4200:4200"
    # volumes:
    #   - ./:/app
    #   - node_modules:/app/node_modules
volumes:
  postgresdb:
    driver: local
  elasticsearchdb:
    driver: local
  node_modules:
    driver: local